development:
  adapter: postgresql
  #postgis_extension: true
  #script_dir: db/postgis
  #schema_search_path: public
  #su_username: postgres
  #su_password: creation
  encoding: unicode
  database: donotcall_development
  pool: 5
  username: ee_web
  password: CFQH6br6yMzLGw

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: localhost
  port: 5432

production:
  adapter: postgresql
  #postgis_extension: true
  #script_dir: db/postgis
  #schema_search_path: public
  #su_username: postgres
  #su_password: creation
  encoding: unicode
  database: donotcall_production
  pool: 5
  username: ee_web
  password: CFQH6br6yMzLGw

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: mv1.ethicalelectric.com
  port: 5432
